### ISSUE TITLE
In case you will be up all night trying to fix this

### ISSUE THREAD

**Issue by iamalismith** [jpreecedev/ssr-state-provider#1]
I slacked you but not sure you'll see it. 
We found the culprit
```const toggleCheckbox = (index, filterGroupIndex) => {
    const newState = { ...props };
```

only does a “shallow” new object
so we were mutating the props (effectively state) within there directly
so we tried: `const newState = JSON.parse(JSON.stringify(props));`
and it worked

**Comment by jonbrightdev** [comment]
@iamalismith mate you are a legend, you just saved me a lot of pain debugging this.  excellent spot!  We need to come up with a more succinct solution for this because parsing and stringifying is slllllllooooowww.  Such a good spot!

**Comment by iamalismith** [comment]
Ha ha no worries, hope you instead focus your time this evening on
consuming more salt! Yeah we need a better way to clone it. I’m not there
tomorrow but hopefully you and scotty can polish it off 👍
